# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 'Open Disclosure Oakland'
email: oaklandopendisclosure@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  We provide transparent, non-partisan campaign contribution and expenditure
  data in an accessible and easy to understand format. We hope this site will
  engage the voting public and raise awareness and accountability. Ultimately,
  this is one step toward shifting politics into a movement of civic engagement
  and ultimate citizen action.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.opendisclosure.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: OpenDisclosureO
github_username:  caciviclab
future: true
permalink: pretty
google_analytics: UA-50973042-1


collections:
  candidates:
    output: true
    permalink: /candidate/:path/
  committees:
    output: true
    permalink: /committee/:path/
  elections:
    output: true
    permalink: /election/:path/
  localities:
    output: true
    permalink: /:path/
  office_elections:
    output: true
    permalink: /office/:path/
  referendums:
    output: true
    permalink: /referendum/:path/

defaults:
  - scope:
      path: ''
    values:
      layout: page
  - scope:
      type: elections
    values:
      layout: ballot
  - scope:
      type: candidates
    values:
      layout: candidate
  - scope:
      type: committees
    values:
      layout: committee
  - scope:
      type: localities
    values:
      layout: locality
  - scope:
      type: office_elections
    values:
      layout: office_election
  - scope:
      type: referendums
    values:
      layout: referendum


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
include:
  - .circleci # Include CircleCI config so gh-pages branch is ignored in CI

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE.md
  - Makefile
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - webpack.config.js
